# Generated by Django 4.1 on 2022-08-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imdb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cast",
            name="movie",
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="imdb.cast"),
        ),
    ]
